device:
  layer: rpi4
  hostname: metacrust-pi4
  user1: gateway
  user1passhash: "$6$S65R/7doKrTNn5QH$yIyxA8w37IHiSXwKyVtLnIvJ/7MrUIi21.UyPkPe7yHnLu.Kgw7LvfdJm4QQkByDKcjreki4KScMJCi0Vaz4c."
  user1sudo: nopasswd

image:
  layer: image-rpios
  name: metacrust-gateway-pi4-v2
  boot_part_size: 200%
  root_part_size: 300%

layer:
  base: metacrust-base
  layout: metacrust-layout
  grow_rootfs: metacrust-grow-rootfs
  network: metacrust-network-runtime
  services: metacrust-services
  remote: metacrust-remote-access

locale:
  timezone: Asia/Karachi
  default: en_US.UTF-8
  keyboard_layout: English (US)
  keyboard_keymap: us

ssh:
  pubkey_user1: /home/hsb/.ssh/id_ed25519.pub
  pubkey_only: y
